name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
    - name: Git - Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Setup - Xcode
      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
    - name: Setup - Ruby and bundler dependencies
      uses: ruby/setup-ruby@v1.57.0
      with:
        ruby-version: 3.0.0-preview1
        bundler-cache: true
    - name: Setup - SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.FASTFILE_SSH_PRIVATE_KEY }}
    - name: Build
      uses: maierj/fastlane-action@v2.0.1
      env:
        RUN_ID: ${{ github.run_id }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      with:
        lane: 'build'
