name: Daily Archive

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  main:
    uses: ./.github/workflows/Fastlane.yml
    with:
      lane_name: daily_archive
      fetch_depth: 20
    secrets:
      fastfile_ssh_private_key: ${{ secrets.FASTFILE_SSH_PRIVATE_KEY }}
      match_ssh_private_key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}
