name: Merge Pull Request

on:
  pull_request:
    branches:
      - 'develop'
    types: [ closed ]

env:
  HAVE_UNIT_TEST: ${{ secrets.HAVE_UNIT_TEST }}

jobs:
  main:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/UnitTest.yml