name: Release

on:
  push:
    branches:
      - 'master'
      - 'main'
  workflow_dispatch:

jobs:
  main:
    uses: ./.github/workflows/Fastlane.yml
    with:
      lane_name: release
    secrets:
      fastfile_ssh_private_key: ${{ secrets.FASTFILE_SSH_PRIVATE_KEY }}
      match_ssh_private_key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}
